source("http://bioconductor.org/biocLite.R")
biocLite(c("Rsamtools", "qvalue", "vegan","CompQuadForm"))
install.packages("devtools")
library(devtools)
install_git("git://github.com/dgarrimar/sQTLseekeR2")
